### PR TITLE
oauth2_token: fix deprecated function call

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi leonardo.rossi@studenti.unipr.it

### CODE REVIEW

**Comment by dvaergiller** [comment]
The reason why we call rand_bytes here is because the already made call to strong_rand_bytes might throw the low_entropy exception. I am worried that an immediate call to the same function may throw the same exception, defeating the purpose of the catch clause.

I agree that the rand_bytes call should probably not be called since it's deprecated. Could we do this in a more bullet proof way? Maybe repeatedly calling the strong_rand_bytes function until it succeeds? How about a tiny delay between the calls to increase the probability of enough entropy? Is it probable enough for this call to fail repeatedly that we should fail at some point?

**Comment by hachreak** [comment]
@dvaergiller what about call [rand_seed(Seed)](http://erlang.org/doc/man/crypto.html) when the exception occur?
See erlang docs:

> Set the seed for PRNG to the given binary. This calls the RAND_seed function from openssl. Only use this if the system you are running on does not have enough "randomness" built in. Normally this is when strong_rand_bytes/1 returns low_entropy

What do you think aboutsomething like:
```erlang
catch
  throw:low_entropy ->
    {MegaSecs, Secs, MicroSecs} = os:timestamp(),
    crypto:rand_seed(list_to_binary(io_lib:format("~p~p~p", [MegaSecs, Secs, MicroSecs]))),
    ?MODULE:strong_rand_bytes_proxy(N)
end

```

**Comment by deadtrickster** [comment]
I believe this code might be more suitable for seed binary generation. At least it's strictly monotonic.

```
Time = erlang:monotonic_time(),
UMI = erlang:unique_integer([monotonic]),
Seed = term_to_binary({Time, UMI}).
```

Source: http://erlang.org/doc/apps/erts/time_correction.html#id79424. "Determine Order of Events with Time of the Event" section.

**Comment by hachreak** [comment]
Thanks @deadtrickster for the help! :smile: 
Do you think it'll be safe do this?
```erlang
    catch
        throw:low_entropy ->
            Time = erlang:monotonic_time(),
            UMI = erlang:unique_integer([monotonic]),
            Seed = term_to_binary({Time, UMI}),
            crypto:rand_seed(Seed),
            % try again with the new seed
           rand_bytes(N) 
    end.
```


@dvaergiller WDYT? Do you like this solution?

**Comment by dvaergiller** [comment]
Yes. This is better than my proposal. This piece of code just turned non-trivial and I would like to have a test that at least runs the code. Let me get back to you with a test proposal.

**Comment by hachreak** [comment]
:+1:

**Comment by hachreak** [comment]
Hi @dvaergiller,
when you have time, could you have a look if the code and test are ok? thanks

p.s. I added a commit to add OTP 19 in the travis matrix.

**Comment by onno-vos-kivra** [comment]
Closing since this PR is no longer relevant.

**Pull request closed without merging**
